### ISSUE TITLE
Google drive file find error

### ISSUE THREAD

**Issue by ngiangre** [ThinkR-open/wedding#26]
After I set the environmental variables and put the toy datasets in my google drive, the app results in an error: 
```
Error in confirm_single_file(file) : 
  `file` identifies more than one Drive file.
```
I traced it to line 37 in app_server.R and it seems like the google drive API takes a long time searching when there's many other files in the drive to search through. When I ran the `googledrive::drive_download` command locally, the file downloaded fine. I'm wondering if you have encountered this issue before? I wasn't able to run the demo on posit cloud. 

I'm just starting my own wedding process and I want to develop a shiny app for the website. I think this app is a great starting point! I also think there's more features in the "shiny world" now that this app could be improved with. I'd love to try a PR to get this app working on my end. Any suggestions on that front?

**Comment by ngiangre** [comment]
I figured out why I had that error (I'm hoping someone in the future may find this useful). I had the sheets both in my drive as well as copies in my shared drive. This resulted in two files with the same name. Removing the shared files fixed the issue. 

Thank you for developing this app! I think I may modify it for my own purposes. If you have any suggestions or wish list in terms of app features, please share them!

**Comment by MargotBr** [comment]
Hello @ngiangre 

Thank you very much for all this information.

Indeed, I think that new users may encounter this issue, and they'll be delighted to learn what's causing it.

At the moment, I don't have much time to feed this app with new features. I hope to find more time soon.

Margot
